[package]
name = "sui-consistent-store-framework"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
scoped-futures.workspace = true
sui-consistent-store.workspace = true
sui-indexer-alt-framework = { workspace = true, default-features = false }
sui-indexer-alt-framework-store-traits.workspace = true
sui-types.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
